- menu_name: "Links"

- name: "NeuroTechX"
  url: "http://www.neurotechx.com/"
  title: "NeuroTechX"

- name: "Slack"
  url: "http://bit.ly/joinslackedu"
  title: "Slack"

- name: "Contribute to EDU"
  url: " http://bit.ly/neurotechedu"
  title: "Contribute to EDU"

- name: "Github"
  url: "https://github.com/NeuroTechX/learn.neurotechedu.com"
  title: "Github"

- name: "README"
  url: "https://github.com/NeuroTechX/learn.neurotechedu.com/blob/gh-pages/README.md"
  title: "README"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap for Google webmaster tools"
